### PR TITLE
Feature Proposal(s): Extended configuration options & Interactive Prompt

### PR DESCRIPTION
**Pull request by varphi-online**
Reading the RSS 2.0 Spec for this project, I realized how many optional elements are allowed, and I wanted to extend that customizability to the user, so I added/moved around some of the config struct to accommodate for this.

Conversely, I absolutely love programs that make set-up fast, easy, and simple, so I have committed an interactive prompt that takes the user through a series of 6 required questions to get right into converting, while simultaneously creating the config file if it wasn't there already, and scaffolding for all the extensible options from above (with `json.Marshal`)
image
image
I just thought this would be nice to provide to possibly less-experienced Linux users who want to use the project 😄

### CODE REVIEW

**Comment by TimoKats** [comment]
Hi @varphi-online , thanks for the PR. Will check it out later this week. One question, could you maybe bulk your commits when you push? 

Not that you have to many commits, but I need to watch my usage of github actions this month lol

**Comment by varphi-online** [comment]
Oh, of course! I apologize, I was unaware that was a limited resource, I will be sure to be more careful in the future with how often I'm pushing commits. Sorry again!

**Comment by TimoKats** [comment]
Hi @varphi-online , I merged a slightly lessened version of your fix. I quite like the idea of an init command, but I kept the config as it is for now. You're credited as a co-author and actually mentioned in the README when it comes to this new command :)

**Comment by varphi-online** [comment]
Hi @TimoKats, glad to hear the init command got added :) Also, thank you for the README credit, I really appreciate it!

**Pull request closed without merging**
